# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
      rules:
        - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
    view:
      view_response_listener:  true
      formats:
        json: true
    exception:
      enabled: true
  #  routing_loader: true
   
  #  exception:
  #      codes:
  #          App\Exception\MyException: 403
      #  messages:
      #      App\Exception\MyException: Forbidden area.
   
